http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      priority: 10
      entryPoints:
        - web
        - websecure
      service: api

    frontend:
      rule: "PathPrefix(`/`)"
      priority: 1
      entryPoints:
        - web
        - websecure
      service: frontend

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:3001"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
