http:
  routers:
    site-d6cbjlrcw092dfy5fwx4p0md-http:
      rule: "Host(`cantaconmigo.hh`)"
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      service: site-d6cbjlrcw092dfy5fwx4p0md

    site-d6cbjlrcw092dfy5fwx4p0md:
      rule: "Host(`cantaconmigo.hh`)"
      entryPoints:
        - https
      tls:
        certResolver: internal-ca
      service: site-d6cbjlrcw092dfy5fwx4p0md

  services:
    site-d6cbjlrcw092dfy5fwx4p0md:
      loadBalancer:
        servers:
          - url: "http://frontend-d6cbjlrcw092dfy5fwx4p0md-225831778211:80"
