http:
  routers:
    site-smm1r5ot3dcm5xvz0kgr6eeu-http:
      rule: "Host(`probablyfine.shallowfordroad.com`)"
      entryPoints:
        - http
      middlewares:
        - redirect-to-https
      service: site-smm1r5ot3dcm5xvz0kgr6eeu

    site-smm1r5ot3dcm5xvz0kgr6eeu:
      rule: "Host(`probablyfine.shallowfordroad.com`)"
      entryPoints:
        - https
      service: site-smm1r5ot3dcm5xvz0kgr6eeu

  services:
    site-smm1r5ot3dcm5xvz0kgr6eeu:
      loadBalancer:
        servers:
          - url: "http://smm1r5ot3dcm5xvz0kgr6eeu-041630115142:3000"
